### ISSUE TITLE
Can't get the Json Data

### ISSUE THREAD

**Issue by ibrahimyucel** [alsenet-labs/mrz-scanner#2]
Hello,
I am grateful to you for this project.But I have a problem with this;can't get the json data.
I have looked your explanation but could'nt understand the "mrz.json".I tried with image name like you said but I'm getting the "No such file or directory" error.
Need your help in this case.
My regards.

**Comment by luxigo** [comment]
Hello,

I mean if there is a result for eg "passport.jpg" it will be stored in "passport.jpg.mrz.json"
Maybe you should specify the full path for the input file, not a relative path.

If you need some support I'm available for hire.
On the other hand [donations via paypal to luc.deschenaux@freesurf.ch](https://www.paypal.com/donate/?token=EQ7DXgefTua1VeESpY1i6udKsb_ze-dxXSqi0Zb3vioPOizC9MA97aPJdWlV_7zvY17xXm) to support my free software developments are always welcome.

Best regards,

Luc Deschenaux

**Comment by stevenspinoza** [comment]
In case someone needs an example:

`mrz2json -d C:\Users\Your_user\your_folder\folder mrz.jpg` space after directory, here the file is in the same folder, otherwise you have to type the whole url
