### ISSUE TITLE
How do I load this library in a React project?

### ISSUE THREAD

**Issue by marbetschar** [alsenet-labs/mrz-scanner#3]
Hi there,

I sucessfuly tested your library in Vanilla JavaScript and I'd like to include it now into a React/webpack project. There I installed it using `npm install`, but now I'm stuck importing and actually using it.

Would highly appreciate any pointers which take me any further.

**Comment by luxigo** [comment]
Sorry the question is more like:
- how do I use a worker with react ?

Learn about workers, then check demo.js to see how the worker is initialized and the application communicate with it.
Then figure out how to use it with react searching for "react worker example" .
