### ISSUE TITLE
No data returns from online demo

### ISSUE THREAD

**Issue by Sotiris-k** [alsenet-labs/mrz-scanner#6]
Hello,

Thank you for your time developing this.

I tried uploading [this sample picture](https://www.doubango.org/webapps/mrz/img/sample1_highres.jpg) to [the online demo](https://alsenet-labs.github.io/mrz-scanner/dist/index.html) and it returns "no roi found".

Am I missing something?

**Comment by polto** [comment]
Hey ! Seems to work if you crop the image to the page with the MRZ. It works well if the image only see that one page.

**Comment by Sotiris-k** [comment]
Hi @polto 

Thank you for your answer.

I tried with another sample which was cropped. 
![1508253342644](https://user-images.githubusercontent.com/4454324/85981808-79331500-b9ed-11ea-9d2e-33399ab7509c.jpg)

There was an error in the parsing of the JSON response.

What seems to be the problem with this one?

**Comment by luxigo** [comment]
The image was not cropped enough and image quality was bad (jpeg artefacts), it worked after cropping more and adjusting color levels with a curve:
 
![image](https://user-images.githubusercontent.com/1018226/93122922-9bbcfc00-f6c7-11ea-95ce-e2d6f1a39b2f.png)
